/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Hello */
        get: operations["hello__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/db-check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check Database */
        get: operations["check_database_db_check_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/buildings/{building_id}/revisions/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Bulk Upload Revision */
        post: operations["bulk_upload_revision_projects__project_id__buildings__building_id__revisions_bulk_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/buildings/{building_id}/revisions/edit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Edit Revision */
        post: operations["edit_revision_projects__project_id__buildings__building_id__revisions_edit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects_projects_get"];
        put?: never;
        /** Create Project */
        post: operations["create_project_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/buildings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Buildings */
        get: operations["list_buildings_projects__project_id__buildings_get"];
        put?: never;
        /** Create Building */
        post: operations["create_building_projects__project_id__buildings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/buildings/{building_id}/floors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Floor */
        post: operations["create_floor_projects__project_id__buildings__building_id__floors_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/buildings/{building_id}/zones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Zone */
        post: operations["create_zone_projects__project_id__buildings__building_id__zones_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/buildings/{building_id}/grid": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Grid */
        post: operations["create_grid_projects__project_id__buildings__building_id__grid_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/materials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Material */
        post: operations["create_material_materials_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Section */
        post: operations["create_section_sections_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/barspec": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Barspec */
        post: operations["create_barspec_barspec_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/buildings/{building_id}/revisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Revisions */
        get: operations["list_revisions_projects__project_id__buildings__building_id__revisions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/buildings/{building_id}/revisions/{rev_id}/objects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Objects */
        get: operations["list_objects_projects__project_id__buildings__building_id__revisions__rev_id__objects_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/buildings/{building_id}/revisions/{rev_id}/objects/{obj_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Object Detail */
        get: operations["get_object_detail_projects__project_id__buildings__building_id__revisions__rev_id__objects__obj_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BarSpecCreate */
        BarSpecCreate: {
            /** Barspec Label */
            barspec_label: string;
            /** Barspec Dia */
            barspec_dia: number;
            /** Barspec Type */
            barspec_type: string;
            /** Barspec Grade */
            barspec_grade: string;
            /** Barspec Weight */
            barspec_weight: number;
        };
        /** BarSpecResponse */
        BarSpecResponse: {
            /** Barspec Id */
            barspec_id: string;
            /** Barspec Label */
            barspec_label: string;
            /** Barspec Dia */
            barspec_dia: number;
            /** Barspec Type */
            barspec_type: string;
            /** Barspec Grade */
            barspec_grade: string;
            /** Barspec Weight */
            barspec_weight: number;
        };
        /** BuildingCreate */
        BuildingCreate: {
            /** Building Name */
            building_name?: string | null;
        };
        /** BuildingResponse */
        BuildingResponse: {
            /** Building Id */
            building_id: string;
            /** Building Name */
            building_name: string | null;
            /** Project Id */
            project_id: string;
        };
        /** BulkUploadRequest */
        BulkUploadRequest: {
            /** Objects */
            objects: components["schemas"]["ObjectCreate"][];
        };
        /** EditRevisionRequest */
        EditRevisionRequest: {
            /** Changed Objects */
            changed_objects?: components["schemas"]["ObjectCreate"][];
            /** Deleted Stable Ids */
            deleted_stable_ids?: string[];
        };
        /** FloorCreate */
        FloorCreate: {
            /** Floor Name */
            floor_name: string;
            /** Elevation */
            elevation: number;
        };
        /** FloorResponse */
        FloorResponse: {
            /** Floor Id */
            floor_id: string;
            /** Floor Name */
            floor_name: string;
            /** Elevation */
            elevation: number;
            /** Building Id */
            building_id: string;
        };
        /** GridCreate */
        GridCreate: {
            /** Grid Label */
            grid_label: string;
            /**
             * Grid Axis
             * @enum {string}
             */
            grid_axis: "x" | "y";
            /** Grid Coord */
            grid_coord: {
                [key: string]: number;
            };
        };
        /** GridResponse */
        GridResponse: {
            /** Grid Id */
            grid_id: string;
            /** Grid Label */
            grid_label: string;
            /** Grid Axis */
            grid_axis: string;
            /** Grid Coord */
            grid_coord: {
                [key: string]: string | number;
            };
            /** Building Id */
            building_id: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MaterialCreate */
        MaterialCreate: {
            /** Mat Name */
            mat_name: string;
            /** Mat Type */
            mat_type: string;
            /** Mat Strength */
            mat_strength: number;
            /** Mat Weight */
            mat_weight: number;
        };
        /** MaterialResponse */
        MaterialResponse: {
            /** Mat Id */
            mat_id: string;
            /** Mat Name */
            mat_name: string;
            /** Mat Type */
            mat_type: string;
            /** Mat Strength */
            mat_strength: number;
            /** Mat Weight */
            mat_weight: number;
        };
        /** ObjectCreate */
        ObjectCreate: {
            /** Is New */
            is_new: boolean;
            /** Obj Mark */
            obj_mark: string;
            /**
             * Obj Type
             * @enum {string}
             */
            obj_type: "column" | "beam" | "wall" | "slab" | "footing" | "stair";
            /** Floor Name */
            floor_name: string;
            /** Zone Label */
            zone_label: string;
            /** Sect Label */
            sect_label: string;
            /** Mat Name */
            mat_name: string;
            /** Geometry Points */
            geometry_points: number[][];
            /** Reinforcements */
            reinforcements?: components["schemas"]["ReinforcementCreate"][];
            /** Stable Id */
            stable_id?: string | null;
        };
        /** ObjectDetail */
        ObjectDetail: {
            /** Obj Id */
            obj_id: string;
            /** Obj Mark */
            obj_mark: string;
            /** Stable Id */
            stable_id: string;
            /** Obj Type */
            obj_type: string;
            /** Change Status */
            change_status: string;
            /** Floor Name */
            floor_name: string;
            /** Zone Label */
            zone_label: string;
            /** Sect Label */
            sect_label: string;
            /** Dimension */
            dimension: {
                [key: string]: string | number;
            };
            /** Mat Name */
            mat_name: string;
            /** Geometry Points */
            geometry_points: number[][];
            /** Reinforcements */
            reinforcements: components["schemas"]["ReinforcementDetail"][];
            quantity: components["schemas"]["QuantityDetail"] | null;
        };
        /**
         * ObjectListItem
         * @description The "Combined View" pattern (D39): foreign keys resolved to their
         *     descriptive values, not returned as bare IDs.
         */
        ObjectListItem: {
            /** Obj Id */
            obj_id: string;
            /** Obj Mark */
            obj_mark: string;
            /** Stable Id */
            stable_id: string;
            /** Obj Type */
            obj_type: string;
            /** Change Status */
            change_status: string;
            /** Floor Name */
            floor_name: string;
            /** Zone Label */
            zone_label: string;
            /** Sect Label */
            sect_label: string;
            /** Mat Name */
            mat_name: string;
        };
        /** ProjectCreate */
        ProjectCreate: {
            /** Project Name */
            project_name?: string | null;
        };
        /** ProjectResponse */
        ProjectResponse: {
            /** Project Id */
            project_id: string;
            /** Project Name */
            project_name: string | null;
        };
        /** QuantityDetail */
        QuantityDetail: {
            /** Qty Sect */
            qty_sect: string;
            /** Qty Bar */
            qty_bar: string;
        };
        /** ReinforcementCreate */
        ReinforcementCreate: {
            /** Barspec Label */
            barspec_label: string;
            /** Bar Role */
            bar_role: string;
            /** Bar Count */
            bar_count: number;
            /** Bar Len */
            bar_len: number;
            /** Bar Space */
            bar_space?: number | null;
            /** Bar Hook Type */
            bar_hook_type?: string | null;
        };
        /** ReinforcementDetail */
        ReinforcementDetail: {
            /** Bar Id */
            bar_id: string;
            /** Barspec Label */
            barspec_label: string;
            /** Barspec Dia */
            barspec_dia: number;
            /** Barspec Grade */
            barspec_grade: string;
            /** Bar Role */
            bar_role: string;
            /** Bar Count */
            bar_count: number;
            /** Bar Len */
            bar_len: number;
            /** Bar Space */
            bar_space: number | null;
            /** Bar Hook Type */
            bar_hook_type: string | null;
        };
        /** RevisionListItem */
        RevisionListItem: {
            /** Rev Id */
            rev_id: string;
            /** Rev Number */
            rev_number: number;
            /** Building Id */
            building_id: string;
        };
        /** RevisionObjectResult */
        RevisionObjectResult: {
            /** Obj Id */
            obj_id: string;
            /** Obj Mark */
            obj_mark: string;
            /** Stable Id */
            stable_id: string;
            /** Change Status */
            change_status: string;
        };
        /** RevisionResponse */
        RevisionResponse: {
            /** Rev Id */
            rev_id: string;
            /** Rev Number */
            rev_number: number;
            /** Objects */
            objects: components["schemas"]["RevisionObjectResult"][];
        };
        /** SectionCreate */
        SectionCreate: {
            /**
             * Obj Type
             * @enum {string}
             */
            obj_type: "column" | "beam" | "wall" | "slab" | "footing" | "stair";
            /** Sect Label */
            sect_label: string;
            /** Dimension */
            dimension: {
                [key: string]: string | number;
            };
        };
        /** SectionResponse */
        SectionResponse: {
            /** Sect Id */
            sect_id: string;
            /** Sect Label */
            sect_label: string;
            /** Obj Type */
            obj_type: string;
            /** Dim */
            dim: {
                [key: string]: string | number;
            };
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** ZoneCreate */
        ZoneCreate: {
            /** Zone Label */
            zone_label: string;
            /** Pour Seq */
            pour_seq: number;
        };
        /** ZoneResponse */
        ZoneResponse: {
            /** Zone Id */
            zone_id: string;
            /** Zone Label */
            zone_label: string;
            /** Pour Seq */
            pour_seq: number;
            /** Building Id */
            building_id: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    hello__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    check_database_db_check_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    bulk_upload_revision_projects__project_id__buildings__building_id__revisions_bulk_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                building_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkUploadRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevisionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_revision_projects__project_id__buildings__building_id__revisions_edit_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                building_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EditRevisionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevisionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_projects_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"][];
                };
            };
        };
    };
    create_project_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_buildings_projects__project_id__buildings_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BuildingResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_building_projects__project_id__buildings_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BuildingCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BuildingResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_floor_projects__project_id__buildings__building_id__floors_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                building_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FloorCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FloorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_zone_projects__project_id__buildings__building_id__zones_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                building_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ZoneCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ZoneResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_grid_projects__project_id__buildings__building_id__grid_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                building_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GridCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GridResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_material_materials_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MaterialCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_section_sections_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SectionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SectionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_barspec_barspec_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BarSpecCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BarSpecResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_revisions_projects__project_id__buildings__building_id__revisions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                building_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevisionListItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_objects_projects__project_id__buildings__building_id__revisions__rev_id__objects_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                building_id: string;
                rev_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObjectListItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_object_detail_projects__project_id__buildings__building_id__revisions__rev_id__objects__obj_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                building_id: string;
                rev_id: string;
                obj_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObjectDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
