/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Hello */
        get: operations["hello__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/db-check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check Database */
        get: operations["check_database_db_check_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/buildings/{building_id}/revisions/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Bulk Upload Revision */
        post: operations["bulk_upload_revision_buildings__building_id__revisions_bulk_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/buildings/{building_id}/revisions/edit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Edit Revision */
        post: operations["edit_revision_buildings__building_id__revisions_edit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BulkUploadRequest */
        BulkUploadRequest: {
            /** Objects */
            objects: components["schemas"]["ObjectCreate"][];
        };
        /** EditRevisionRequest */
        EditRevisionRequest: {
            /** Changed Objects */
            changed_objects?: components["schemas"]["ObjectCreate"][];
            /** Deleted Stable Ids */
            deleted_stable_ids?: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ObjectCreate */
        ObjectCreate: {
            /** Is New */
            is_new: boolean;
            /** Obj Mark */
            obj_mark: string;
            /**
             * Obj Type
             * @enum {string}
             */
            obj_type: "col" | "beam" | "wall" | "slab";
            /** Floor Id */
            floor_id: string;
            /** Zone Id */
            zone_id: string;
            /** Sect Id */
            sect_id: string;
            /** Mat Id */
            mat_id: string;
            /** Geometry Points */
            geometry_points: number[][];
            /** Reinforcements */
            reinforcements?: components["schemas"]["ReinforcementCreate"][];
            /** Stable Id */
            stable_id?: string | null;
        };
        /** ReinforcementCreate */
        ReinforcementCreate: {
            /** Barspec Id */
            barspec_id: string;
            /** Bar Role */
            bar_role: string;
            /** Bar Count */
            bar_count: number;
            /** Bar Len */
            bar_len: number;
            /** Bar Space */
            bar_space?: number | null;
            /** Bar Hook Type */
            bar_hook_type?: string | null;
        };
        /** RevisionObjectResult */
        RevisionObjectResult: {
            /** Obj Id */
            obj_id: string;
            /** Obj Mark */
            obj_mark: string;
            /** Stable Id */
            stable_id: string;
            /** Change Status */
            change_status: string;
        };
        /** RevisionResponse */
        RevisionResponse: {
            /** Rev Id */
            rev_id: string;
            /** Rev Number */
            rev_number: number;
            /** Objects */
            objects: components["schemas"]["RevisionObjectResult"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    hello__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    check_database_db_check_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    bulk_upload_revision_buildings__building_id__revisions_bulk_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                building_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkUploadRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevisionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_revision_buildings__building_id__revisions_edit_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                building_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EditRevisionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevisionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
