"""add identities table

Revision ID: 2383810277a3
Revises: bc750298834d
Create Date: 2026-09-15 19:58:29.711730

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2383810277a3'
down_revision: str | Sequence[str] | None = 'bc750298834d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('identities',
    sa.Column('stable_id', sa.String(), nullable=False),
    sa.Column('ifc_global_id', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('stable_id'),
    sa.UniqueConstraint('ifc_global_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('identities')
    # ### end Alembic commands ###
