"""add reinforcements and quantity tables

Revision ID: 65461096482c
Revises: 921bab19d6f8
Create Date: 2026-09-15 20:01:44.570576

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '65461096482c'
down_revision: str | Sequence[str] | None = '921bab19d6f8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quantity',
    sa.Column('qty_id', sa.String(), nullable=False),
    sa.Column('obj_id', sa.String(), nullable=False),
    sa.Column('qty_sect', sa.Integer(), nullable=False),
    sa.Column('qty_bar', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['obj_id'], ['objects.obj_id'], ),
    sa.PrimaryKeyConstraint('qty_id')
    )
    op.create_table('reinforcements',
    sa.Column('bar_id', sa.String(), nullable=False),
    sa.Column('obj_id', sa.String(), nullable=False),
    sa.Column('barspec_id', sa.String(), nullable=False),
    sa.Column('bar_role', sa.String(), nullable=False),
    sa.Column('bar_count', sa.Integer(), nullable=False),
    sa.Column('bar_len', sa.Integer(), nullable=False),
    sa.Column('bar_space', sa.Integer(), nullable=True),
    sa.Column('bar_hook_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['barspec_id'], ['barspec.barspec_id'], ),
    sa.ForeignKeyConstraint(['obj_id'], ['objects.obj_id'], ),
    sa.PrimaryKeyConstraint('bar_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reinforcements')
    op.drop_table('quantity')
    # ### end Alembic commands ###
