"""replace member with object, restructure around stable id and rev id

Revision ID: 921bab19d6f8
Revises: 2383810277a3
Create Date: 2026-09-15 19:59:58.544788

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '921bab19d6f8'
down_revision: str | Sequence[str] | None = '2383810277a3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('objects',
    sa.Column('obj_id', sa.String(), nullable=False),
    sa.Column('obj_mark', sa.String(), nullable=False),
    sa.Column('stable_id', sa.String(), nullable=False),
    sa.Column('rev_id', sa.String(), nullable=False),
    sa.Column('change_status', sa.String(), nullable=False),
    sa.Column('obj_type', sa.String(), nullable=False),
    sa.Column('floor_id', sa.String(), nullable=False),
    sa.Column('zone_id', sa.String(), nullable=False),
    sa.Column('sect_id', sa.String(), nullable=False),
    sa.Column('mat_id', sa.String(), nullable=False),
    sa.Column('geometry_points', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.CheckConstraint("change_status IN ('added', 'modified', 'unchanged', 'deleted', 'restored')", name='ck_objects_change_status'),
    sa.ForeignKeyConstraint(['floor_id'], ['floors.floor_id'], ),
    sa.ForeignKeyConstraint(['mat_id'], ['materials.mat_id'], ),
    sa.ForeignKeyConstraint(['rev_id'], ['revisions.rev_id'], ),
    sa.ForeignKeyConstraint(['sect_id', 'obj_type'], ['sections.sect_id', 'sections.obj_type'], name='fk_objects_sect_id_obj_type'),
    sa.ForeignKeyConstraint(['stable_id'], ['identities.stable_id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.zone_id'], ),
    sa.PrimaryKeyConstraint('obj_id')
    )
    op.drop_table('members')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('members',
    sa.Column('member_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('member_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('storey_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('dimension_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('material_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('zone_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('geometry_points', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['dimension_id', 'member_type'], ['sections.sect_id', 'sections.obj_type'], name=op.f('fk_members_dimension_type')),
    sa.ForeignKeyConstraint(['material_id'], ['materials.mat_id'], name=op.f('members_material_id_fkey')),
    sa.ForeignKeyConstraint(['storey_id'], ['floors.floor_id'], name=op.f('members_storey_id_fkey')),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.zone_id'], name=op.f('members_zone_id_fkey')),
    sa.PrimaryKeyConstraint('member_id', name=op.f('members_pkey'))
    )
    op.drop_table('objects')
    # ### end Alembic commands ###
