"""add revisions table with rev_number linearity

Revision ID: bc750298834d
Revises: 9b52c9ab1906
Create Date: 2026-09-15 19:57:43.754451

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'bc750298834d'
down_revision: str | Sequence[str] | None = '9b52c9ab1906'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revisions',
    sa.Column('rev_id', sa.String(), nullable=False),
    sa.Column('building_id', sa.String(), nullable=False),
    sa.Column('rev_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.building_id'], ),
    sa.PrimaryKeyConstraint('rev_id'),
    sa.UniqueConstraint('building_id', 'rev_number', name='uq_revisions_building_rev_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('revisions')
    # ### end Alembic commands ###
